# check latest version on: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
kubectl_version: v1.34

# allemaal macbook waar je geluid van kan regelen op het netwerk :(
# sudo dnf remove pipewire-config-raop


# TODO add
# sudo yum install -y https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm

# $ sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
# $ curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo
# $ sudo dnf makecache
# $ sudo dnf install powershell
# $ sudo dnf install mssql-tools18
# $ echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc

# rpm packages to install
dnf_packages:
  - dnfdragora
  - awscli2
  - mkcert
  - htop
  - policycoreutils-devel # needed for ESET build (selinux Makefile)
  - gimp
  - inkscape
  - pandoc
  - google-chrome-stable
  - texlive-scheme-full
  - keepassxc
  - dropbox
  - steam
  - libreoffice
  - openal-soft-devel
  - git
  - gcc-plugin-devel
  - screen
  - gparted
  - libmpc-devel
  - kate
  - gcc-c++
  - gcc-c++-riscv64-linux-gnu
  - ncurses-devel
  - nano
  - flex
  - bison
  - SDL2-devel
  - SDL3-devel
  - libglvnd-devel
  - libdvdcss
  - "@Development Libraries"
  - chromedriver
  - python3-defusedxml
  - meld
  - swig
  - openssl-devel-engine
  - gnutls-devel
  - sshpass
  - python3-pykcs11
  - python3-kubernetes

# flatpak packages to install
flatpak_packages:
  # - com.jetbrains.Rider
  - com.discordapp.Discord
  - app.freelens.Freelens
  - org.kde.kdenlive
  - org.signal.Signal
  - org.soapui.SoapUI
