- name: Install virtualization
  hosts: localhost
  tasks:

    - name: Check if virt-manager is already enabled
      ansible.builtin.shell: |
        set -o pipefail
        rpm -qa | grep -a "virt-manager" || echo "go"
      changed_when: false
      register: rpm

    - name: Install virtualization
      ansible.builtin.command: |
        dnf group install --with-optional virtualization -y
      become: true
      changed_when: true
      when: rpm.stdout == "go"

    - name: Enable service libvirtd
      become: true
      ansible.builtin.systemd_service:
        name: libvirtd
        state: started
        enabled: true
