- name: Install VSCode
  hosts: localhost
  tasks:
    - name: Import Slack key
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: https://slack.com/gpg/slack_pubkey_20240822.gpg

    - name: Creating /etc/yum.repos.d/slack.repo
      become: true
      ansible.builtin.copy:
        dest: "/etc/yum.repos.d/slack.repo"
        content: |
          [slack]
          name=slack
          baseurl=https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64
          enabled=1
          gpgcheck=0
          gpgkey=https://packagecloud.io/gpg.key
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Install the latest version of slack
      ansible.builtin.dnf:
        name: slack
        state: present
      become: true
