- name: Install VSCode
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Import Microsoft key
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Creating /etc/yum.repos.d/vscode.repo
      become: true
      ansible.builtin.copy:
        dest: "/etc/yum.repos.d/vscode.repo"
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          autorefresh=1
          type=rpm-md
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Install the latest version of VS Code
      ansible.builtin.dnf:
        name: code
        state: present
      become: true
