- name: Install Docker CE / helm / kubectl
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Check if docker repo is present
      ansible.builtin.shell: |
        set -o pipefail
        dnf repolist | grep -a "docker" || echo "go"
      args:
        executable: /bin/bash
      changed_when: false
      register: rpm

    - name: Add docker repo
      ansible.builtin.shell: |
        dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
      changed_when: true
      become: true
      when: rpm.stdout == "go"

    - name: Install a list of packages
      become: true
      ansible.builtin.dnf5:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - helm
        state: present

    - name: Enable service docker
      become: true
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true

    - name: Creating /etc/yum.repos.d/kubernetes.repo
      become: true
      ansible.builtin.copy:
        dest: "/etc/yum.repos.d/kubernetes.repo"
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/{{ kubectl_version }}/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/{{ kubectl_version }}/rpm/repodata/repomd.xml.key
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Import kubectl key
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: https://pkgs.k8s.io/core:/stable:/{{ kubectl_version }}/rpm/repodata/repomd.xml.key

    - name: Install the latest version of kubectl
      ansible.builtin.dnf:
        name: kubectl
        state: present
      become: true
