- name: Install swap codecs and install hardware firmware
  hosts: localhost
  tasks:

    - name: Check if ffmpeg-free is present
      ansible.builtin.shell: |
        set -o pipefail
        rpm -qa | grep -a "ffmpeg-free" || echo "gone"
      changed_when: false
      register: rpm

    - name: Swap ffmpeg-free ffmpeg
      ansible.builtin.shell: |
        dnf swap ffmpeg-free ffmpeg --allowerasing -y
      register: result
      changed_when: '"Nothing to do." not in result.stdout'
      become: true
      when: not rpm.stdout == "gone"

    - name: Update multimedia group
      ansible.builtin.command: dnf update @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
      become: true
      register: result
      changed_when: '"Nothing to do." not in result.stdout'
      when: rpm.stdout == "1"

    # TODO add intel check and installation
    - name: Check if amdgpu is preset
      ansible.builtin.shell: |
        set -o pipefail
        lspci -k | grep -EA3 'VGA|3D|Display' | grep amdgpu || echo "go"
      changed_when: false
      register: amdgpu

    - name: Swap mesa drivers
      ansible.builtin.shell: dnf swap mesa-va-drivers mesa-va-drivers-freeworld -y && dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld -y
      become: true
      register: result
      changed_when: '"Nothing to do." not in result.stdout'
      when: not amdgpu.stdout == "go"

    - name: Install firmwares from rpmfusion-nonfree-tainted
      ansible.builtin.shell: dnf --repo=rpmfusion-nonfree-tainted install "*-firmware" -y
      become: true
      register: result
      changed_when: '"Nothing to do." not in result.stdout'
