# default to work config


- name: Config git
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Creating /home/opvolger/.gitconfig
      ansible.builtin.copy:
        dest: "/home/opvolger/.gitconfig"
        content: |
          [user]
            name = Bas Magré

          [include]
            path = ~/.gitconfig.zorg

          [includeIf "gitdir:**/code/**/.git"]
            path = ~/.gitconfig.code
        owner: opvolger
        group: opvolger
        mode: u=rw,g=r,o=r

    - name: Creating /home/opvolger/.gitconfig
      ansible.builtin.copy:
        dest: "/home/opvolger/.gitconfig.zorg"
        content: |
          [user]
            email = bas.magre@topicus.nl
          [core]
            sshcommand = ssh -i ~/.ssh/id_ed25519
        owner: opvolger
        group: opvolger
        mode: u=rw,g=r,o=r

    - name: Creating /home/opvolger/.gitconfig
      ansible.builtin.copy:
        dest: "/home/opvolger/.gitconfig.code"
        content: |
          [user]
            email = bas@opvolger.net
          [core]
            sshcommand = ssh -i ~/.ssh/id_github_prive
        owner: opvolger
        group: opvolger
        mode: u=rw,g=r,o=r